#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set JAVA_HOME
export JAVA_HOME=$(/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home)
# Customize to your needs...
export EDITOR=vim
# Aliases
alias nssh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q'
alias nscp='scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q'
alias nsftp='sftp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -q'
alias ssh-nokey='ssh -o PubkeyAuthentication=no -q'
alias ssh_config='$EDITOR ~/.ssh/config'
alias k='kubectl'
#complete -o default -F __start_kubectl k

alias dps='docker ps'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

echo "Testing a message"
